# Generated by Django 4.0 on 2023-11-29 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='品番')),
            ],
        ),
        migrations.CreateModel(
            name='inv_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('comment', models.CharField(max_length=50, verbose_name='備考')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('product_num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product_num', verbose_name='品番')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customuser', verbose_name='ユーザー')),
            ],
        ),
    ]
